security:
    encoders:
        PwdMgr\Model\Entity\User:
          algorithm: bcrypt
          cost: 13

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_db:
            entity: { class: PwdMgr\Model\Entity\User, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            http_basic: ~
            pattern: /.*
            provider: user_db
            form_login:
                    provider: user_db
                    login_path: /auth/login
                    check_path: /auth/login_check
                    remember_me: true
            logout:
                path: /auth/logout
                target: /
            #remember_me:
            #    key: MiPassphrase
            #    lifetime: 1800
            #    path: /.*
            #    domain: ~
            security: true
            anonymous: true
            switch_user: true

    access_control:
        - { path: /auth/passwd/.*, roles: [ROLE_USER, IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: /auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /, roles: [ROLE_USER] }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

    acl:
        connection: default
