services:
    # aliases for auto-wiring
    container: @service_container
    em: @doctrine.orm.entity_manager
    entity_manager: @doctrine.orm.entity_manager
    dispatcher: @event_dispatcher
    security: @security.context

    kernel.listener.ajax_authentication_listener:
        class: Cwd\GenericBundle\Event\AjaxAuthenticationListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 250 }
